`compute_intersection` with CGAL
luca-heltai/fsi-suite pull request #1
Opened 2022-03-11 08:03 UTC by fdrmrc

In this PR I've added CGAL and the `compute_intersection(cell0,cell1,degree,mapping0,mapping1)` free function. Some simple tests in co-dimension one have been added.  Some more non-trivial tests in co-dimension 0 are in progress.

I would add the actual test with Fictitious Domain method in a separate PR, once this one is okay.

2022-03-11 10:37 UTC, fdrmrc commented
Co-dimension 0 tests have been added.

2022-03-13 12:04 UTC, luca-heltai requested changes
Can you rebase on top of the new master? I have forced push on main to remove from the repository the lecture notes. I've left some comments. As soon as you split header and source, and leave cgal include out of the header, we can merge, and make corrections later.

2022-03-13 17:52 UTC, fdrmrc commented on include/compute_intersection_of_cells.h
> +// CGAL header files and typedefs
Thanks, so this .h file will contain only the `#include "compute_linear_transformation.h"`and the header guards, as all functions are using CGAL

2022-03-13 20:35 UTC, fdrmrc commented on include/compute_intersection_of_cells.h
> +typedef CGAL_Polygon::Point_2              CGAL_Point;
Yes

2022-03-15 12:57 UTC, merged