Compute tria intersections
luca-heltai/fsi-suite pull request #2
Opened 2022-03-17 10:14 UTC by fdrmrc

- Fixed numbering of vertices in rectangle-rectangle intersection 0fbcacd13f20c660dc1f885d66783f0f289eea6d

 - Added new function `intersect_and_get_quads()`. It returns a ```std::vector<
  std::tuple<typename dealii::Triangulation<dim0, spacedim>::active_cell_iterator,typename dealii::Triangulation<dim1, spacedim>::active_cell_iterator,Quadrature<spacedim>>>```

- Extended namespace `dealii::NonMatching` so that it contains `compute_intersection` (that works for cells only) and the new functions for triangulations

2022-03-18 18:56 UTC, luca-heltai requested changes

2022-03-18 18:56 UTC, luca-heltai commented on include/compute_intersections_of_tria.h
> +
```suggestion
```

2022-03-18 18:56 UTC, luca-heltai commented on include/compute_intersections_of_tria.h
> +
```suggestion
```

2022-03-18 18:56 UTC, luca-heltai commented on include/compute_intersections_of_tria.h
> +  intersect_and_get_quads(
I would rather call also this function `compute_intersection`, leveraging C++ overloading capabilities.

Can you add a documentation for the function, and keep both functions in the same header file?

2022-03-18 23:27 UTC, fdrmrc commented
Thanks Luca for the review. I added operator overloading and documentation for `compute_intersection`. I renamed the files and fixed the #includes in the `gtests` folder.

2022-03-19 15:32 UTC, luca-heltai commented
Documentation is still missing. Would you mind adding some documentation? Remember: someone who has never seen this before, should understand what it does, and how to use it. :)

2022-03-20 07:47 UTC, luca-heltai requested changes

2022-03-20 07:47 UTC, luca-heltai commented on source/compute_intersections.cc
> +   */
This should go in the header file, not in the source file. :)

2022-03-20 07:47 UTC, luca-heltai commented on source/compute_intersections.cc
> +   */
Same here. The documentation goes together with the declaration, not in the cc file, but in the h file.

2022-03-20 07:48 UTC, luca-heltai commented
If you need help with the rebase, let me know, and I'll do it for you (or explain to you how to do it, so you know it next time).

2022-03-23 08:22 UTC, luca-heltai requested changes

2022-03-23 08:22 UTC, luca-heltai commented on source/compute_intersections.cc
> +
Add an `#else`  and `#endif` here, where you have the default implementations that simply throws exceptions saying that you need CGAL, and then instantiate all of the functions irrespective of wether CGAL exists or not. This makes sure you don't get errors in user codes at link time, but just at run time.

2022-03-29 08:58 UTC, fdrmrc commented
- I added here `create_coupling_sparsity_pattern_with_exact_intersections()` . As you suggested, this depends on the output of `compute_intersection()`, which is a vector of tuples.
- `compute_intersection` has been improved by avoiding to store the intersected cells in a `std::set`, so that only a double for over the trees is needed. 

This sparsity pattern has been checked in `reduced_lagrange.cc`, and runs fine

2022-03-29 14:57 UTC, luca-heltai commented on source/compute_intersections.cc
> +                  "but cmake could not find it."));
```suggestion
template <int dim0, int dim1, int spacedim>
  std::vector<std::tuple<
    typename dealii::Triangulation<dim0, spacedim>::active_cell_iterator,
    typename dealii::Triangulation<dim1, spacedim>::active_cell_iterator,
    dealii::Quadrature<spacedim>>>
  compute_intersection(const GridTools::Cache<dim0, spacedim> &,
                       const GridTools::Cache<dim1, spacedim> &,
                       const unsigned int                     )
  {
Assert(false,
       ExcMessage("This function needs CGAL to be installed, "
                  "but cmake could not find it."));
                  return {};
}
     
                 template <int dim0, int dim1, int spacedim>
  dealii::Quadrature<spacedim>
  compute_intersection(
    const typename dealii::Triangulation<dim0, spacedim>::cell_iterator &,
    const typename dealii::Triangulation<dim1, spacedim>::cell_iterator &,
    const unsigned int                                                  ,
    const dealii::Mapping<dim0, spacedim> &,
    const dealii::Mapping<dim1, spacedim> &)
  {
               Assert(false,
       ExcMessage("This function needs CGAL to be installed, "
                  "but cmake could not find it."));
                  return {};
                  }
```

2022-03-30 06:43 UTC, merged